# Generated by Django 5.0.7 on 2026-07-01 07:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("production_date", models.DateField()),
                ("supplier", models.CharField(max_length=200)),
                ("received_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("dimensions", models.CharField(max_length=50)),
                (
                    "pieces_per_carton",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sku"], name="inventory_t_sku_2c07e9_idx"),
                    models.Index(
                        fields=["category"], name="inventory_t_categor_54ede6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIVING", "Receiving"),
                            ("DISPATCH", "Dispatch"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cartons_change", models.IntegerField()),
                ("loose_pieces_change", models.IntegerField()),
                ("previous_cartons", models.PositiveIntegerField()),
                ("previous_loose_pieces", models.PositiveIntegerField()),
                ("new_cartons", models.PositiveIntegerField()),
                ("new_loose_pieces", models.PositiveIntegerField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.batch",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.tile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cartons",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "loose_pieces",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("location", models.CharField(db_index=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="inventory.batch",
                    ),
                ),
                (
                    "tile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="inventory.tile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batch",
            name="tile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="inventory.tile",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("old_values", models.JSONField(default=dict)),
                ("new_values", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="inventory.movement",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["movement"], name="inventory_a_movemen_2c99a3_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="inventory_a_timesta_628f6b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["tile"], name="inventory_m_tile_id_a919a0_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["batch"], name="inventory_m_batch_i_f441c0_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(
                fields=["movement_type"], name="inventory_m_movemen_6d66c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(
                fields=["created_at"], name="inventory_m_created_b65c6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["tile"], name="inventory_i_tile_id_c260e1_idx"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["batch"], name="inventory_i_batch_i_c705bb_idx"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["location"], name="inventory_i_locatio_e4ba1b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                fields=("tile", "batch", "location"), name="unique_tile_batch_location"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["batch_number"], name="inventory_b_batch_n_6c5580_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["tile"], name="inventory_b_tile_id_294abc_idx"),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["is_active"], name="inventory_b_is_acti_222ecd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("tile", "batch_number"), name="unique_tile_batch"
            ),
        ),
    ]
