# Generated by Django 5.0.7 on 2026-07-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_tilecatalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tiles/"),
        ),
    ]
