# Generated by Django 5.0.7 on 2026-07-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_tile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="brand",
            field=models.CharField(
                choices=[
                    ("goodwill", "Goodwill"),
                    ("crown_crane", "Crown Crane"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tile",
            name="series",
            field=models.CharField(
                blank=True,
                help_text="Collection/series name (e.g. Cosmos, Noble, Glaze)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tile",
            name="tier",
            field=models.CharField(
                choices=[("standard", "Standard"), ("premium", "Premium")],
                default="standard",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="tile",
            index=models.Index(fields=["brand"], name="inventory_t_brand_143a00_idx"),
        ),
        migrations.AddIndex(
            model_name="tile",
            index=models.Index(fields=["tier"], name="inventory_t_tier_4f5703_idx"),
        ),
    ]
