# Generated by Django 5.0.7 on 2026-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_tile_brand_tile_series_tile_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="coverage_per_box",
            field=models.CharField(
                blank=True, help_text="e.g. 1.92 sqm per box", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="tile",
            name="finish",
            field=models.CharField(
                blank=True,
                help_text="e.g. Matt, Gloss, Matt or Gloss available",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tile",
            name="thickness",
            field=models.CharField(blank=True, help_text="e.g. 8-10mm", max_length=50),
        ),
        migrations.AddField(
            model_name="tile",
            name="tile_type",
            field=models.CharField(
                blank=True,
                help_text="e.g. Ceramic Floor Tile, Porcelain Wall Tile",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tile",
            name="use_case",
            field=models.CharField(
                blank=True, help_text="e.g. Living rooms, bedrooms", max_length=200
            ),
        ),
    ]
