# Generated by Django 5.0.7 on 2026-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_tilecatalog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="syncconflict",
            new_name="inventory_s_model_n_e16ac6_idx",
            old_name="inventory_s_model_n_2efaa1_idx",
        ),
        migrations.RenameIndex(
            model_name="syncconflict",
            new_name="inventory_s_resolve_bb4008_idx",
            old_name="inventory_s_resolve_d59b3f_idx",
        ),
        migrations.RenameIndex(
            model_name="syncconflict",
            new_name="inventory_s_created_c4cfa0_idx",
            old_name="inventory_s_created_2a54e2_idx",
        ),
        migrations.AddField(
            model_name="tile",
            name="is_mix",
            field=models.BooleanField(
                default=False,
                help_text="Mixed/temporary bin entry, not a standard product",
            ),
        ),
    ]
