# Generated by Django 5.0.7 on 2026-07-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_tile_is_mix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="inventory.movement",
            ),
        ),
    ]
