# Generated by Django 5.0.7 on 2026-07-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_make_auditlog_movement_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="line_total",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
