# Generated by Django 5.0.7 on 2026-07-13 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchaseorder_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='received_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
